services:
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo-data:/data/db

  api:
    build:
      context: ./league-tool-backend
    ports:
      - "3040:3040"
    env_file:
      - ./league-tool-backend/.env
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
      - redis

  web:
    build:
      context: ./league-tool-csr
    ports:
      - "4200:80"

  redis:
    image: redis:7
    container_name: league-tool-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data: